platformName = android
platformVersion = 12
UDID = adb-08433312AK070338-nxjUdM._adb-tls-connect._tcp
appPackage = com.flowcomptech.ecommdemo2
appActivity = com.flowcomptech.ecommdemo2.MainActivity
inCorrectMobile = yogi@gmail.com
inCorrectPass = abc123
correctUserName = 8374033532
correctedPassword = yogi123